"""empty message

Revision ID: 51f7bc4a0b0a
Revises: 4f28a146d9cb
Create Date: 2022-12-11 22:18:34.148801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f7bc4a0b0a'
down_revision = '4f28a146d9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cart',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    op.drop_table('Cart')
    # ### end Alembic commands ###
